// =============================================
// Fitness_And_Sports_Data.js — Shared Product Database
// =============================================

const allProducts = [
    {
        id: "FS_ProSeriesTreadmillZ1",
        name: "Pro-Series Treadmill Z1",
        category: "Gym & Strength",
        categoryKey: "gym",
        price: 899,
        originalPrice: 1200,
        rating: 4.9,
        reviews: 1200,
        img: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?q=80&w=400&h=300&fit=crop",
        badge: "Signature",
        badgeClass: "badge-new",
        desc: "Commercial-grade motor and advanced cushioning for the ultimate running experience."
    },
    {
        id: "FS_AdjustableDumbbellSet",
        name: "Adjustable Dumbbell Set",
        category: "Gym & Strength",
        categoryKey: "gym",
        price: 249,
        originalPrice: 349,
        rating: 4.8,
        reviews: 3400,
        img: "https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?q=80&w=400&h=300&fit=crop",
        badge: "Best Seller",
        badgeClass: "badge-best",
        desc: "Replace 15 sets of weights with one compact system."
    },
    {
        id: "FS_PremiumYogaMatPro",
        name: "Premium Yoga Mat Pro",
        category: "Yoga & Pilates",
        categoryKey: "yoga",
        price: 75,
        originalPrice: 95,
        rating: 5.0,
        reviews: 850,
        img: "https://images.unsplash.com/photo-1592432678886-dd0452fba3d1?q=80&w=400&h=300&fit=crop",
        badge: "Eco-Friendly",
        badgeClass: "badge-new",
        desc: "Sustainable materials and non-slip surface."
    },
    {
        id: "FS_PerformanceFootball",
        name: "Performance Football",
        category: "Outdoor Sports",
        categoryKey: "outdoor",
        price: 45,
        originalPrice: null,
        rating: 4.7,
        reviews: 580,
        img: "https://images.unsplash.com/photo-1510566337590-2fc1f21d0faa?q=80&w=400&h=300&fit=crop",
        badge: "Match Grade",
        badgeClass: "badge-deal",
        desc: "High-performance aerodynamic design for official matches."
    },
    {
        id: "FS_BoxingGlovesPro",
        name: "Boxing Gloves Pro",
        category: "Combat Sports",
        categoryKey: "combat",
        price: 85,
        originalPrice: 110,
        rating: 4.8,
        reviews: 2100,
        img: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?q=80&w=400&h=300&fit=crop",
        badge: "Top Rated",
        badgeClass: "badge-best",
        desc: "Professional protection and wrist support."
    },
    {
        id: "FS_EcoYogaBlock",
        name: "Eco Yoga Block",
        category: "Yoga & Pilates",
        categoryKey: "yoga",
        price: 15,
        originalPrice: 22,
        rating: 4.5,
        reviews: 420,
        img: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?q=80&w=400&h=300&fit=crop",
        badge: "New",
        badgeClass: "badge-new",
        desc: "High-density foam for support and alignment."
    },
    {
        id: "FS_SpeedJumpRope",
        name: "Speed Jump Rope",
        category: "Gym & Strength",
        categoryKey: "gym",
        price: 12,
        originalPrice: null,
        rating: 4.6,
        reviews: 1500,
        img: "https://images.unsplash.com/photo-1590502160462-094ba45283fc?q=80&w=400&h=300&fit=crop",
        badge: "Amazon Choice",
        badgeClass: "badge-best",
        desc: "Tangle-free design with ball bearings for smooth rotation."
    },
    {
        id: "FS_ResistanceBandSet",
        name: "Resistance Band Set",
        category: "Gym & Strength",
        categoryKey: "gym",
        price: 35,
        originalPrice: 70,
        rating: 4.4,
        reviews: 980,
        img: "https://images.unsplash.com/photo-1517130591727-4422e661be48?q=80&w=400&h=300&fit=crop",
        badge: "50% OFF",
        badgeClass: "badge-deal",
        desc: "Stackable bands for all fitness levels."
    },
    {
        id: "FS_KettlebellSet",
        name: "Cast Iron Kettlebell Set",
        category: "Gym & Strength",
        categoryKey: "gym",
        price: 120,
        originalPrice: 150,
        rating: 4.8,
        reviews: 890,
        img: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=400&h=300&fit=crop",
        badge: "Trending",
        badgeClass: "badge-best",
        desc: "Premium cast iron kettlebells for full-body workouts."
    },
    {
        id: "FS_SwimGoggles",
        name: "Pro Racing Swim Goggles",
        category: "Aquatic Fitness",
        categoryKey: "aquatic",
        price: 25,
        originalPrice: 35,
        rating: 4.7,
        reviews: 450,
        img: "https://images.unsplash.com/photo-1595089304381-8314e3efb6fb?q=80&w=400&h=300&fit=crop",
        badge: "Anti-Fog",
        badgeClass: "badge-new",
        desc: "Clear vision with advanced anti-fog technology."
    },
    {
        id: "FS_FoamRoller",
        name: "Deep Tissue Foam Roller",
        category: "Recovery Gear",
        categoryKey: "recovery",
        price: 28,
        originalPrice: null,
        rating: 4.6,
        reviews: 1100,
        img: "https://images.unsplash.com/photo-1600881333168-2ef49b341f30?q=80&w=400&h=300&fit=crop",
        badge: "Essential",
        badgeClass: "badge-best",
        desc: "Muscle recovery and tension relief."
    },
    {
        id: "FS_Basketball",
        name: "Indoor/Outdoor Basketball",
        category: "Outdoor Sports",
        categoryKey: "outdoor",
        price: 38,
        originalPrice: 50,
        rating: 4.8,
        reviews: 2200,
        img: "https://images.unsplash.com/photo-1519861531473-9200262188bf?q=80&w=400&h=300&fit=crop",
        badge: "Official Size",
        badgeClass: "badge-deal",
        desc: "Superior grip and durability for any court."
    }
];
