// =============================================
// Homesmart_Data.js — Shared Product Database
// Single source of truth for both landing page & All Products
// =============================================

const allProducts = [
    // === Hero / Featured Products ===
    { id: "HS_EmeraldCeramicPotSet", name: "Emerald Ceramic Pot Set", price: 129.99, originalPrice: 189.99, category: "Cookware", categoryKey: "cookware", badge: "Best Seller", badgeClass: "badge-best", img: "../assets/cookware_category_green_1775381016223.png", desc: "Eco-friendly ceramic with non-stick coating. Set of 5 pots and pans for healthy, oil-free cooking.", rating: 4.8, reviews: 3200 },
    { id: "HS_SmartKitchenCombo", name: "Smart Kitchen Combo", price: 199, originalPrice: 399, category: "Kitchen", categoryKey: "kitchen", badge: "50% OFF", badgeClass: "badge-deal", img: "https://images.unsplash.com/photo-1556910110-ad52744d7c1f?q=80&w=400&h=300&fit=crop", desc: "Digital 8-in-1 kitchen workstation including high-speed blender, food processor, and smart-weighing bowl.", rating: 4.7, reviews: 2450 },
    { id: "HS_LuxurySofaSetLux", name: "Luxury Sofa Set Lux", price: 1200, originalPrice: 1800, category: "Furniture", categoryKey: "furniture", badge: "Top Pick", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=400&h=300&fit=crop", desc: "Hand-finished premium velvet upholstery with high-density foam cushions and a solid mahogany frame.", rating: 4.9, reviews: 1890 },
    { id: "HS_NordicMinimalistVase", name: "Nordic Minimalist Vase", price: 32, originalPrice: null, category: "Home Decor", categoryKey: "decor", badge: "Trending", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1581783598307-5bbe6ed40e5a?q=80&w=400&h=300&fit=crop", desc: "Matte-finish ceramic vase with organic line work. A timeless centerpiece reflecting Scandinavian design simplicity.", rating: 4.5, reviews: 1560 },
    { id: "HS_BambooServingTray", name: "Bamboo Serving Tray", price: 24.50, originalPrice: 35, category: "Kitchen", categoryKey: "kitchen", badge: "Best Deal", badgeClass: "badge-deal", img: "https://images.unsplash.com/photo-1481833761820-0509d3217039?q=80&w=400&h=300&fit=crop", desc: "Hand-crafted sustainable bamboo with raised edges and reinforced handles. Ideal for charcuterie and coffee service.", rating: 4.4, reviews: 2100 },
    { id: "HS_VelvetCushionSet", name: "Velvet Cushion Set", price: 45, originalPrice: 65, category: "Furnishing", categoryKey: "furnishing", badge: "Best Seller", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&h=300&fit=crop", desc: "Set of 4 plush velvet cushions with hidden zippers. Includes hypoallergenic inserts for maximum comfort.", rating: 4.6, reviews: 2340 },

    // === Mosquito Net & Insect Protection ===
    { id: "HS_RoyalMosquitoNetKing", name: "Royal Mosquito Net King", price: 39.99, originalPrice: 59, category: "Insect Protection", categoryKey: "insect", badge: "Best Seller", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1632345031435-072fc985bc31?q=80&w=400&h=300&fit=crop", desc: "Extra-fine honeycomb mesh with a reinforced bottom border. 360-degree protection for king-size beds.", rating: 4.7, reviews: 4500 },
    { id: "HS_WindowMeshScreenKit", name: "Window Mesh Screen Kit", price: 18, originalPrice: 25, category: "Insect Protection", categoryKey: "insect", badge: "Essential", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1621371107530-9b3602167d4f?q=80&w=400&h=300&fit=crop", desc: "Self-adhesive magnetic frame kit with high-transparency fiberglass mesh. Fully customizable for any window size.", rating: 4.3, reviews: 3200 },

    // === Modern Home Decor ===
    { id: "HS_AbstractWallArtCanvas", name: "Abstract Wall Art Canvas", price: 89, originalPrice: 129, category: "Home Decor", categoryKey: "decor", badge: "New", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1549490349-8643362247b5?q=80&w=400&h=300&fit=crop", desc: "Set of 3 hand-painted abstract canvas panels. Vibrant emerald gold textures that create a focal point in any room.", rating: 4.8, reviews: 890 },
    { id: "HS_FloatingShelfSet", name: "Floating Shelf Set", price: 55, originalPrice: 75, category: "Home Decor", categoryKey: "decor", badge: "Popular", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1594498653385-d5172b532c00?q=80&w=400&h=300&fit=crop", desc: "Three-piece solid oak floating shelves with invisible bracket mounts. Holds up to 10kg each.", rating: 4.6, reviews: 1780 },
    { id: "HS_AromaticReedDiffuser", name: "Aromatic Reed Diffuser", price: 28, originalPrice: null, category: "Home Decor", categoryKey: "decor", badge: "Trending", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1602928294711-536f9ae94098?q=80&w=400&h=300&fit=crop", desc: "Premium essential oil aromatic reeds. Includes 200ml of fragrance and 10 natural rattan reeds for slow diffusion.", rating: 4.4, reviews: 2560 },

    // === Premium Lighting ===
    { id: "HS_CrystalChandelierModern", name: "Crystal Chandelier Modern", price: 249, originalPrice: 399, category: "Lighting", categoryKey: "lighting", badge: "Premium", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1517705008128-361805f42e86?q=80&w=400&h=300&fit=crop", desc: "K9 crystal prismatic pendants on a brushed steel frame. Features dimmable LED integration and high-end refractivity.", rating: 4.9, reviews: 670 },
    { id: "HS_SmartLEDStrip10m", name: "Smart LED Strip 10m", price: 35, originalPrice: 49, category: "Lighting", categoryKey: "lighting", badge: "Best Deal", badgeClass: "badge-deal", img: "https://images.unsplash.com/photo-1558239023-b8a4814a7e56?q=80&w=400&h=300&fit=crop", desc: "16 million colors with voice control through Alexa. Strong self-adhesive backing and multi-zone light effects.", rating: 4.5, reviews: 5600 },
    { id: "HS_MinimalTableLamp", name: "Minimal Table Lamp", price: 42, originalPrice: null, category: "Lighting", categoryKey: "lighting", badge: "New", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1507473884658-6697bc933075?q=80&w=400&h=300&fit=crop", desc: "Sculptural iron frame with a sandblasted finish and natural linen drum shade. Hand-touch brightness adjustment.", rating: 4.3, reviews: 1890 },

    // === Eco Storage ===
    { id: "HS_BambooStorageBoxSet", name: "Bamboo Storage Box Set", price: 34, originalPrice: 49, category: "Storage", categoryKey: "storage", badge: "Eco-Friendly", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1521128182236-407137f8ea6b?q=80&w=400&h=300&fit=crop", desc: "Set of 4 stackable hand-woven bamboo boxes. Breathable design perfect for linens, towels, or wardrobe organization.", rating: 4.6, reviews: 2100 },
    { id: "HS_GlassStorageJars6pc", name: "Glass Storage Jars 6pc", price: 29, originalPrice: null, category: "Storage", categoryKey: "storage", badge: "Kitchen Must", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1584286595398-a59f21d313f5?q=80&w=400&h=300&fit=crop", desc: "Crystal clear borosilicate glass jars with airtight silicone-sealed bamboo lids. Ranging from 250ml to 2 Liters.", rating: 4.7, reviews: 3800 },

    // === Luxury Bathroom ===
    { id: "HS_RainShowerHeadGold", name: "Rain Shower Head Gold", price: 89, originalPrice: 139, category: "Bathroom", categoryKey: "bathroom", badge: "Luxury", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1559839734-2b71cf197ec2?q=80&w=400&h=300&fit=crop", desc: "Wide 12-inch rainfall surface with a stunning brushed gold finish. Easy-clean silicone nozzles and high-pressure tech.", rating: 4.8, reviews: 1450 },
    { id: "HS_BambooBathCaddy", name: "Bamboo Bath Caddy", price: 38, originalPrice: 55, category: "Bathroom", categoryKey: "bathroom", badge: "Spa Vibes", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=400&h=300&fit=crop", desc: "Solid bamboo construction with adjustable wing length. Features wine glass slots and tablet prop for the ultimate bath experience.", rating: 4.5, reviews: 2300 },

    // === Drinkware ===
    { id: "HS_DoubleWallGlassSet", name: "Double-Wall Glass Set", price: 32, originalPrice: 45, category: "Drinkware", categoryKey: "drinkware", badge: "Best Seller", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1574633405260-2495b54630a1?q=80&w=400&h=300&fit=crop", desc: "Set of 6 insulated borosilicate glasses. Double-wall technology prevents condensation and keeps beverages at optimal temperature.", rating: 4.7, reviews: 3400 },
    { id: "HS_CeramicMugCollection", name: "Ceramic Mug Collection", price: 24, originalPrice: null, category: "Drinkware", categoryKey: "drinkware", badge: "Handmade", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1514228742587-6b1558fbed39?q=80&w=400&h=300&fit=crop", desc: "Set of 4 artisan-crafted mugs with a reactive glaze finish. Each piece features unique subtle variations in tone.", rating: 4.4, reviews: 2890 },

    // === Designer Furniture ===
    { id: "HS_MidCenturyAccentChair", name: "Mid-Century Accent Chair", price: 349, originalPrice: 499, category: "Furniture", categoryKey: "furniture", badge: "Designer", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=400&h=300&fit=crop", desc: "Walnut-finish legs with premium textured boucle fabric. A stylish statement piece for your living room or study.", rating: 4.8, reviews: 780 },
    { id: "HS_IndustrialCoffeeTable", name: "Industrial Coffee Table", price: 189, originalPrice: 269, category: "Furniture", categoryKey: "furniture", badge: "Popular", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?q=80&w=400&h=300&fit=crop", desc: "Solid reclaimed wood tabletop paired with matte black steel legs. Durable industrial build with adjustable feet.", rating: 4.6, reviews: 1560 },

    // === Home Covers ===
    { id: "HS_SofaCoverStretchFit", name: "Sofa Cover Stretch Fit", price: 45, originalPrice: 65, category: "Home Covers", categoryKey: "covers", badge: "Best Seller", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1550226122-241551ad3ffb?q=80&w=400&h=300&fit=crop", desc: "Jacquard weave stretchable sofa protector. Features anti-slip foam anchors and elastic bottom for a custom, tailored look.", rating: 4.5, reviews: 5200 },
    { id: "HS_WaterproofMattressProtector", name: "Waterproof Mattress Protector", price: 29, originalPrice: 39, category: "Home Covers", categoryKey: "covers", badge: "Essential", badgeClass: "badge-deal", img: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=400&h=300&fit=crop", desc: "Deep-pocketed breathable protector with a noiseless TPU backing. Hypoallergenic cotton surface protects against spills and allergens.", rating: 4.7, reviews: 6100 },

    // === Hardware & Tools ===
    { id: "HS_PremiumDrillKit20V", name: "Premium Drill Kit 20V", price: 129, originalPrice: 179, category: "Hardware Tools", categoryKey: "hardware", badge: "Pro Grade", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1504148455328-c376907d081c?q=80&w=400&h=300&fit=crop", desc: "Powerful 20V brushless motor with 2.0Ah lithium-ion battery. Includes a 50-piece comprehensive bit set.", rating: 4.8, reviews: 2340 },
    { id: "HS_WallMountingToolkit", name: "Wall Mounting Toolkit", price: 22, originalPrice: null, category: "Hardware Tools", categoryKey: "hardware", badge: "Must Have", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=400&h=300&fit=crop", desc: "Level, stud finder, anchors, and screws. Everything to hang frames and shelves perfectly.", rating: 4.4, reviews: 3600 },

    // === Furnishing & Textiles ===
    { id: "HS_LinenTableRunner", name: "Linen Table Runner", price: 22, originalPrice: 32, category: "Furnishing", categoryKey: "furnishing", badge: "Elegant", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1534073828943-f801091bb18c?q=80&w=400&h=300&fit=crop", desc: "100% stone-washed linen runner. Heavyweight fabric with decorative hemstitch detail for upscale dining.", rating: 4.5, reviews: 1890 },
    { id: "HS_CottonThrowBlanket", name: "Cotton Throw Blanket", price: 55, originalPrice: 79, category: "Furnishing", categoryKey: "furnishing", badge: "Cozy Pick", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1512418490979-92798cec352a?q=80&w=400&h=300&fit=crop", desc: "Soft organic cotton throw with a traditional waffle weave. Features fringed edges and breathable thermal properties.", rating: 4.7, reviews: 2100 },

    // === Mats & Rugs ===
    { id: "HS_HandwovenJuteRug", name: "Handwoven Jute Rug 5x7", price: 89, originalPrice: 129, category: "Mats & Decor", categoryKey: "mats", badge: "Natural", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1575414003591-ece8d0416c7a?q=80&w=400&h=300&fit=crop", desc: "Eco-friendly natural jute fiber rug. Hand-braided for durability and a warm, rustic aesthetic.", rating: 4.6, reviews: 1340 },
    { id: "HS_AntiFatigueKitchenMat", name: "Anti-Fatigue Kitchen Mat", price: 35, originalPrice: 49, category: "Mats & Decor", categoryKey: "mats", badge: "Comfort+", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=400&h=300&fit=crop", desc: "Premium 3/4 inch ergonomic mat. High-rebound foam core reduces strain on joints during long standing tasks.", rating: 4.5, reviews: 4200 },

    // === Pooja Needs ===
    { id: "HS_BrassPoojaThaliSet", name: "Brass Pooja Thali Set", price: 49, originalPrice: 69, category: "Pooja Needs", categoryKey: "pooja", badge: "Sacred", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?q=80&w=400&h=300&fit=crop", desc: "Solid brass plate with detailed filigree edge. Set includes deepak, agarbatti stand, and roli katori.", rating: 4.8, reviews: 2890 },
    { id: "HS_CamphorIncenseCollection", name: "Camphor & Incense Collection", price: 15, originalPrice: null, category: "Pooja Needs", categoryKey: "pooja", badge: "Daily Use", badgeClass: "badge-deal", img: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?q=80&w=400&h=300&fit=crop", desc: "High-purity Bhimseni camphor paired with hand-rolled Mysore Sandalwood dhoop sticks.", rating: 4.4, reviews: 5600 },

    // === Bath Linen ===
    { id: "HS_EgyptianCottonTowelSet", name: "Egyptian Cotton Towel Set", price: 65, originalPrice: 89, category: "Bath Linen", categoryKey: "bathlinen", badge: "Luxury", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1563298723-dcfebaa392e3?q=80&w=400&h=300&fit=crop", desc: "6-piece set of 800 GSM Egyptian cotton towels. Features long-staple fibers for superior absorbency and fluffiness.", rating: 4.8, reviews: 3100 },
    { id: "HS_BambooFiberBathSheet", name: "Bamboo Fiber Bath Sheet", price: 28, originalPrice: null, category: "Bath Linen", categoryKey: "bathlinen", badge: "Eco Pick", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1594503799639-650081d60bed?q=80&w=400&h=300&fit=crop", desc: "Oversized bath sheet made from an organic bamboo-cotton blend. Naturally antimicrobial and fast-drying.", rating: 4.5, reviews: 2340 },

    // === Urban Gardening ===
    { id: "HS_HerbGardenStarterKit", name: "Herb Garden Starter Kit", price: 34, originalPrice: 49, category: "Gardening", categoryKey: "gardening", badge: "Grow Green", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=400&h=300&fit=crop", desc: "All-in-one starter kit including peat pots, soil disks, and labels for 6 essential culinary herbs.", rating: 4.6, reviews: 2670 },
    { id: "HS_SelfWateringPlanter3pc", name: "Self-Watering Planter 3pc", price: 42, originalPrice: 59, category: "Gardening", categoryKey: "gardening", badge: "Smart", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1592150621344-7164ff0e687e?q=80&w=400&h=300&fit=crop", desc: "Triple set of modern self-watering pots. Features a water level indicator for easy plant maintenance.", rating: 4.7, reviews: 1890 },
    { id: "HS_MatteBlackPlanter", name: "Matte Black Planter", price: 34, originalPrice: null, category: "Gardening", categoryKey: "gardening", badge: "Minimal", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=400&h=300&fit=crop", desc: "Ceramic pot with drainage hole and bamboo saucer. 20cm diameter for medium plants.", rating: 4.3, reviews: 1200 },

    // === Wall Art ===
    { id: "HS_PeelStickWallDecals", name: "Peel & Stick Wall Decals", price: 19, originalPrice: 29, category: "Wall Art", categoryKey: "wallart", badge: "Fun Pick", badgeClass: "badge-deal", img: "https://images.unsplash.com/photo-1583847268964-b28dc2f51ac9?q=80&w=400&h=300&fit=crop", desc: "Premium vinyl botanical wall stickers. Easy to apply, reposition, and remove without damaging wall paint.", rating: 4.4, reviews: 3400 },
    { id: "HS_3DFoamWallPanels10pc", name: "3D Foam Wall Panels 10pc", price: 45, originalPrice: 65, category: "Wall Art", categoryKey: "wallart", badge: "3D Effect", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1513519245088-0e12902e15ca?q=80&w=400&h=300&fit=crop", desc: "High-density PE foam panels with a realistic white brick texture. Features thermal insulation and sound reduction.", rating: 4.5, reviews: 2100 },

    // === Cleaning ===
    { id: "HS_CordlessVacuumPro", name: "Cordless Vacuum Pro", price: 179, originalPrice: 249, category: "Cleaning", categoryKey: "cleaning", badge: "Best Seller", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1558317374-067fb5f30001?q=80&w=400&h=300&fit=crop", desc: "Lightweight cordless stick vacuum with a 250W brushless motor. Multi-stage filtration and LED floor lights.", rating: 4.8, reviews: 4500 },
    { id: "HS_SpinMopBucketSystem", name: "Spin Mop Bucket System", price: 39, originalPrice: 55, category: "Cleaning", categoryKey: "cleaning", badge: "Essential", badgeClass: "badge-deal", img: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=400&h=300&fit=crop", desc: "360-degree spinning wringer with 2 microfiber heads. Stainless steel basket, splash-free design.", rating: 4.5, reviews: 5800 },

    // === Dining ===
    { id: "HS_CeramicDinnerSet24pc", name: "Ceramic Dinner Set 24pc", price: 89, originalPrice: 129, category: "Dining", categoryKey: "dining", badge: "Complete Set", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1616046229412-f04646270b80?q=80&w=400&h=300&fit=crop", desc: "Comprehensive 24-piece dinnerware set. Hand-painted ceramic with an elegant matte glaze finish for upscale dining rooms.", rating: 4.7, reviews: 1670 },
    { id: "HS_StainlessCutlerySet30pc", name: "Stainless Cutlery Set 30pc", price: 49, originalPrice: 69, category: "Dining", categoryKey: "dining", badge: "Premium", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1542601906990-b4d3f66f913e?q=80&w=400&h=300&fit=crop", desc: "Mirror-finish 18/10 stainless steel set. Ergonomically designed with balanced weight and elegant curves.", rating: 4.6, reviews: 2340 },

    // === Home Utilities ===
    { id: "HS_SmartPowerStrip6Port", name: "Smart Power Strip 6-Port", price: 35, originalPrice: 49, category: "Utilities", categoryKey: "utilities", badge: "Smart Home", badgeClass: "badge-new", img: "https://images.unsplash.com/photo-1631581891961-9851fb3c91a1?q=80&w=400&h=300&fit=crop", desc: "App-controlled power center with 4 independent AC outlets and 2 high-speed USB ports. Includes surge protection and energy monitoring.", rating: 4.5, reviews: 3200 },
    { id: "HS_DigitalKitchenScale", name: "Digital Kitchen Scale", price: 22, originalPrice: null, category: "Utilities", categoryKey: "utilities", badge: "Essential", badgeClass: "badge-best", img: "https://images.unsplash.com/photo-1594385208974-2e75f9d8a847?q=80&w=400&h=300&fit=crop", desc: "Ultra-precise digital scale with a tempered glass platform. Features unit conversion and a high-contrast backlit LCD.", rating: 4.4, reviews: 4100 },
    { id: "HS_WoodenCoasterSet", name: "Wooden Coaster Set", price: 15, originalPrice: 22, category: "Utilities", categoryKey: "utilities", badge: "Value Pack", badgeClass: "badge-deal", img: "https://images.unsplash.com/photo-1563298723-dcfebaa392e3?q=80&w=400&h=300&fit=crop", desc: "Set of 6 handcrafted acacia wood coasters. Treated with moisture-resistant finish and features non-slip felt pads.", rating: 4.3, reviews: 2800 }
];
